baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Kontakt"
weight                 = -130
identifier             = "kontakt"
url                    = "/kontakt/"

[[menu.main]]
name                   = "Portfolio"
weight                 = -110
identifier             = "portfolio"
url                    = "/portfolio/"

[[menu.main]]
name                   = "About"
weight                 = -120
identifier             = "about"
url                    = "/about/"