baseURL = "http://hugotestsite.theherman.dk/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"
publishDir = "docs"

[params]
extracssfiles          = [ "/css/override.css" ]

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Kontakt"
weight                 = -100
identifier             = "kontakt"
url                    = "/kontakt/"

[[menu.main]]
name                   = "Portfolio"
weight                 = -110
identifier             = "portfolio"
url                    = "/portfolio/"

[[menu.main]]
name                   = "About"
weight                 = -120
identifier             = "about"
url                    = "/about/"